#!/bin/sh

# git config --local core.hooksPath .githooks/
set -e

#=== 'prev-commit' solution by o_O Tync
commit=$(git log --pretty="id:%h author:%an committer:%cn timestamp:%ci")
commit_msg=$(echo "$commit" | head -1)

# Write it
echo "prev_commit='$commit_msg'\n" > version.txt
