#!/bin/sh

# git config --local core.hooksPath .githooks/
set -e

#=== 'prev-commit' solution by o_O Tync
#commit_hash=$(git rev-parse --verify HEAD)
commit=$(git log -1 --pretty="%h %an %cn %ci")
commit_msg=$(echo "$commit" | head -1)

# Write it
echo "prev_commit='$commit_msg'\n" > version.txt
