<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>aspnet-de.jweschenfelder.KSFP.Web-d04dbdec-c875-44e1-8956-aae28fd00ca5</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\js\webgl\three\docs\**" />
    <Compile Remove="wwwroot\js\webgl\three\examples\jsm\cameras\**" />
    <Compile Remove="wwwroot\js\webgl\three\examples\jsm\libs\**" />
    <Compile Remove="wwwroot\js\webgl\three\examples\jsm\lights\**" />
    <Compile Remove="wwwroot\js\webgl\three\examples\jsm\lines\**" />
    <Content Remove="wwwroot\js\webgl\three\docs\**" />
    <Content Remove="wwwroot\js\webgl\three\examples\jsm\cameras\**" />
    <Content Remove="wwwroot\js\webgl\three\examples\jsm\libs\**" />
    <Content Remove="wwwroot\js\webgl\three\examples\jsm\lights\**" />
    <Content Remove="wwwroot\js\webgl\three\examples\jsm\lines\**" />
    <EmbeddedResource Remove="wwwroot\js\webgl\three\docs\**" />
    <EmbeddedResource Remove="wwwroot\js\webgl\three\examples\jsm\cameras\**" />
    <EmbeddedResource Remove="wwwroot\js\webgl\three\examples\jsm\libs\**" />
    <EmbeddedResource Remove="wwwroot\js\webgl\three\examples\jsm\lights\**" />
    <EmbeddedResource Remove="wwwroot\js\webgl\three\examples\jsm\lines\**" />
    <None Remove="wwwroot\js\webgl\three\docs\**" />
    <None Remove="wwwroot\js\webgl\three\examples\jsm\cameras\**" />
    <None Remove="wwwroot\js\webgl\three\examples\jsm\libs\**" />
    <None Remove="wwwroot\js\webgl\three\examples\jsm\lights\**" />
    <None Remove="wwwroot\js\webgl\three\examples\jsm\lines\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="13.0.1" />
    <PackageReference Include="Blazor.Bootstrap" Version="3.1.1" />
    <PackageReference Include="Blazor.Extensions.Canvas" Version="1.1.1" />
    <PackageReference Include="BlazorCaptcha" Version="1.6.0" />
    <PackageReference Include="BlazorStrap" Version="5.2.101" />
    <PackageReference Include="BlazorStrap.Extensions.BSDataTable" Version="1.5.1" />
    <PackageReference Include="BlazorStrap.V5" Version="5.2.101" />
    <PackageReference Include="Microsoft.AspNetCore.Components.QuickGrid.EntityFrameworkAdapter" Version="8.0.10" />
    <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client" Version="8.0.8" />
    <PackageReference Include="Microsoft.AspNetCore.SignalR.Client.Core" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.8" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.5" />
    <PackageReference Include="System.ServiceModel.Syndication" Version="8.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\de.jweschenfelder.KSFP.Shared\de.jweschenfelder.KSFP.Shared.csproj" />
  </ItemGroup>

</Project>
